name: Update arXiv Summary

on:
  push:
    paths:
      - 'arxiv_links.json'
      - 'update_arxiv_summary.py'
  workflow_dispatch:

jobs:
  update_summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 markdown2 pillow
          pip install arxiv
          pip install pyyaml PyMuPDF
          pip install -U -q google-generativeai==0.7.0

      - name: Run update script
        run: python update_arxiv_summary.py --google_api_key ${{ secrets.GOOGLE_API }}

      - name: Push new arxiv_summary.md
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Github Action Automatic Update arxiv_summary.md"
          files: README.md images/ previous_links.json
          rebase: 'true'
          name: ${{ secrets.USER_NAME }}
          email: ${{ secrets.USER_EMAIL }}